import { parse } from "node-html-parser";
import { publicHost } from "./env";
import { MILISECONDS_PER_SECOND } from "./consts";

export async function generateXml(url: URL): Promise<string> {
    const apiUrl = new URL("https://" + url.host);
    apiUrl.pathname = url.pathname;
    apiUrl.searchParams.set("page", "dapi");
    try {
        apiUrl.searchParams.set("s", url.searchParams.get("page")!);
    } catch {
        throw Error("URL did not contain a 'page' parameter.");
    }
    apiUrl.searchParams.set("limit", "50");
    apiUrl.searchParams.set("q", "index");
    const tags = url.searchParams.get("tags");
    if (tags)
    {
        apiUrl.searchParams.set("tags", tags);
    }

    let xml = `<?xml version="1.0" encoding="utf-8"?>
    <feed xmlns="http://www.w3.org/2005/Atom">
    <title>%feedTitle</title>
    <link href="https://${publicHost}/rss.xml" rel="self"/>
    <link href="https://${url.host}"/>
    <id>${url.toString()}</id>
    <author>
      <name>%author</name>
    </author>
    <subtitle>Booru feed generated by https://${publicHost}</subtitle>
    <generator>booruss</generator>
`;

    if (url.searchParams.get("page") === "post") {
        let feedTitle = "";
        if (tags) {
            feedTitle += `${tags} on `;
        }
        feedTitle += url.host;
        xml = xml.replaceAll("%feedTitle", feedTitle);
        xml = xml.replaceAll("%author", tags || "");

        xml += await getPostEntries(apiUrl);
    } else {
        throw Error("Error fetching posts.");
    }

    xml += "</feed>";
    return xml;
}

export async function getPostEntries(apiUrl: URL): Promise<string> {
    const page = await fetch(apiUrl);
    const text = await page.text();
    return parse(text)
        .querySelectorAll("post")
        .map(post => {
            const id = post.getAttribute("id");
            const postLink = `https://${apiUrl.host}/index.php?page=post&s=view&id=${id}`;
            const updated = new Date(parseInt(post.getAttribute("change")!) * MILISECONDS_PER_SECOND);
            const published = post.getAttribute("created_at");
            const fileUrl = post.getAttribute("file_url");
            return `<entry>
            <title>${id}</title>
            <link href="${postLink}" />
            <id>${postLink}</id>
            <updated>${updated.toISOString()}</updated>
            <published>${published}</published>
            <content type="html"><![CDATA[<img src="${fileUrl}" />]]></content>
            </entry>`;
        })
        .join("\n");
}
